[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  function = "proxy"
  path = "/go/*"

[[plugins]]
  package = "@netlify/plugin-nextjs"
